name: CI
on:
  push:
  pull_request:

jobs:
  bench:
    name: VRASED - ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target: [
          'make run',
          './B-1-dma-translation.sh',
          './B-2-key-size.sh',
          './C-2-stack-pointer.sh',
          './C-3-auth-timing.sh',
          './C-4-nemesis.sh',
          './C-5-dma-sc.sh',
          './D-hw-mod-proof.sh',
          './D-soundness-and-security-proof.sh',
        ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install bison pkg-config gawk clang flex gcc-msp430 iverilog expect-dev libffi-dev -y
      - name: Run test bench
        run: cd scripts && ${{ matrix.target }}
